name: 📋 Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  release:
    name: 📋 Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v7.0.1
        with:
          ref: ${{ inputs.version }}
          fetch-depth: 0
          fetch-tags: true

      - name: 📝 Generate changelog
        id: changelog
        uses: requarks/changelog-action@v1.10.3
        with:
          token: ${{ github.token }}
          tag: ${{ inputs.version }}
          excludeTypes: build,docs,other,style
          writeToFile: false

      - name: 📦 Create Release
        uses: ncipollo/release-action@v1.21.0
        with:
          allowUpdates: true
          draft: false
          tag: ${{ inputs.version }}
          name: ${{ inputs.version }}
          body: ${{ steps.changelog.outputs.changes }}